### ISSUE TITLE
FireFox call event Twice

### ISSUE THREAD

**Issue by flexuus** [mikaturunen/ng-onload#10]
Hi,

do you know the issue, that FireFox fires the passed function twice?
Do you have some approaches?

**Comment by panuhorsmalahti** [comment]
I don't see how this could be happening, but the directive could remove the event listener after the first "load" event.

**Comment by mikaturunen** [comment]
Also as per suggestion; changed the behaviour in `0.5.0` to follow call once and then remove pattern with `one`. 
- https://docs.angularjs.org/api/ng/function/angular.element, "one()" -> http://api.jquery.com/one/
