### ISSUE TITLE
Bower Main Should Point At Non-Minified Version

### ISSUE THREAD

**Issue by mtpultz** [mikaturunen/ng-onload#11]
Bower main is for automated tooling and shouldn't be the minified version since the tooling is typically set on --production to minify all dependencies, but as is the minified file will be reminified.

**Comment by mtpultz** [comment]
I posted a PR #13  updating main to point at /release/ng-onload.js instead of minified version, and added extra gulp task with dependency on es6to5 to force sequencing.

**Comment by mtpultz** [comment]
If you are okay with this PR is it possible to bump a minor release?

**Comment by mikaturunen** [comment]
Sounds like a plan! I'll do a release once I get off work. Thanks for the PR man.

**Comment by mikaturunen** [comment]
And super sorry mate, was busy and forgot. Doing the merge + release now. Gimme a sec.

**Comment by mikaturunen** [comment]
Done. Release out in the wild, version `0.5.0` just went live and can be found from `bower`. Please, enjoy and thanks again for the the contribution. I always appreciate the support!
