### ISSUE TITLE
Error resolving gulp when using webpack

### ISSUE THREAD

**Issue by mkhanal** [mikaturunen/ng-onload#15]
~~~
ERROR in /project/~/ng-onload/gulpfile.js
Module not found: Error: Cannot resolve module 'gulp' in /project/node_modules/ng-onload
 @ /project/~/ng-onload/gulpfile.js 1:11-26
~~~

**Comment by mikaturunen** [comment]
Not webpack compatible, you're free to provide the PR for it. Thanks.

**Comment by mikaturunen** [comment]
And just to be clear, the fix should be fairly easy, change `package.json`property `main` to resolve to `release/ng-onload.min.js`. I just don't have a setup to test it so not going to fix it.
