### ISSUE TITLE
npm will only give me 0.2.1?

### ISSUE THREAD

**Issue by zbend** [mikaturunen/ng-onload#19]
npm can not find v 0.3.0.

Thanks.

**Comment by mikaturunen** [comment]
holy hell, completely forgot to release in NPM. Thanks for the hint. I will release this on NPM today, fixing this issue. Sorry about this. Totally my fault.

**Comment by feitzi** [comment]
@mikaturunen  it seams that the package still isn't released??

**Comment by mikaturunen** [comment]
Seems like I literally can't remember to do the most simple things. Sorry, again.

Now it's released and should be found from NPM.

```
time: { 
  modified: '2017-04-19T13:45:53.011Z',
  created: '2015-05-21T16:58:35.916Z',
  '0.2.1': '2015-05-21T16:58:35.916Z',
  '0.3.0': '2017-04-19T13:45:53.011Z',
  '0.7.0': '2017-04-19T15:37:05.815Z' 
}
```
