### ISSUE TITLE
calling ng-onload when iframe url changes

### ISSUE THREAD

**Issue by jaime-ez** [mikaturunen/ng-onload#20]
Hi, why you use [`element.one`](https://github.com/mikaturunen/ng-onload/blob/master/lib/ng-onload.js#L30) and not `element.on`?
With `element.on` the callback gets called as many times as the iframe is loaded... which I think is a desirable behavior - at least for my use case. Are there any drawbacks of using `element.on` ?
Thanks!

**Comment by mikaturunen** [comment]
Originally it was with `element.on` and it was changed to accommodate the behavior only once due to this issue https://github.com/mikaturunen/ng-onload/issues/10. 

Can you test the behaviour with Firefox and we'll see if we want to change it to `.on`?

**Comment by jaime-ez** [comment]
Hi, sorry for taking so long to reply.
I tested it on Firefox 55.0.2 (64-bit) and the event is called only once, I think it's safe to go back to `.on`

**Comment by mikaturunen** [comment]
That's excellent. Want to make a PR from it?

**Comment by jaime-ez** [comment]
Done :)

On a side note...I found a way to get the same result from using this library with a one line expression:  

` <iframe src="index.test.html" onload="angular.element(this).scope().helloTest(this.src)"></iframe>`

**Comment by anthonyvialleton** [comment]
Hello @mikaturunen , what about the PR made by @jaime-ez  ?
