### ISSUE TITLE
syntax error in Internet Explorer

### ISSUE THREAD

**Issue by alainib** [mikaturunen/ng-onload#4]
Hello. I got a syntax error in Internet Explorer (it work on mozilla or chrome)

I try to change the syntaxe with the follow code i still have an error : 

On IE I have an errror "80020101" on Jquery 

```
    angular.module("ngOnload", []).directive('ngOnload', function () {
    return {
        restrict: "A",
        scope: {
            callback: "&ngOnload"
        },
        link: function(scope, element, attrs){
            var location = element.length > 0 && element[0].contentWindow ?
                element[0].contentWindow.location : undefined;

            // hooking up the onload event - calling the callback on load event
            element.on('load', scope.callback({
                contentLocation: location
            }));
        }
    };
});
```

Any suggestion are welcome Thanks

**Comment by mikaturunen** [comment]
It's currently ES5 but did you originally have everything compiling to ES5?

**Comment by alainib** [comment]
thanks for the fast answer.
Sorry but what did you mean by compiling ?

I'm not compiling anythink, I just use angular 1.5 with standard javascript. 
It's work nice on Mozilla  & Chrome but not on IE ( even if i change mode to quirk or 8 / 10 ).

thanks

**Comment by mikaturunen** [comment]
Well let me go about this differently; are you using the examples directly? As in do you use const / let definitions or just "var" definitions?

**Comment by alainib** [comment]
i use "var" and not "let" in my code
I "translate" your code to a syntax that i use for my directives but i have a new error with Jquery (80020101)  : 

```
angular.module("ngOnload", []).directive('ngOnload', function () {
return {
    restrict: "A",
    scope: {
        callback: "&ngOnload"
    },
    link: function(scope, element, attrs){
        var location = element.length > 0 && element[0].contentWindow ?
            element[0].contentWindow.location : undefined;

        // hooking up the onload event - calling the callback on load event
        element.on('load', scope.callback({
            contentLocation: location
        }));
    }
};
});
```

**Comment by steffenmalisi** [comment]
I came across the same issue. But it was because i used /lib/ng-onload.js directly (using my own uglifier) and not the compiled version from /release. Maybe @alainib did the same. Then IE runs into a syntax error as reported.
But if you use the compiled version in /release everything is fine for me.
If anyone wants a pure Javascript solution (no compiling, not uglified), you could go with that

<pre>
<code>
angular.module("ngOnload", []).directive("ngOnload", function () {
    return {
        restrict: "A",
        scope: {
            callback: "&ngOnload"
        },
        link: function(scope, element, attrs){
            var location = element.length > 0 && element[0].contentWindow ?
                element[0].contentWindow.location : undefined;
            // hooking up the onload event - calling the callback on load event
            element.on("load", function() {scope.callback({
                el: location
            })});
        }
    };
});
</code>
</pre>

**Comment by alainib** [comment]
many thnaks @eazee 
your code fix the problem 

i write 
'element.on('load', scope.callback({'        instead of : 
'element.on("load", function() {scope.callback({'
