### ISSUE TITLE
Bower file shows version 0.2.6

### ISSUE THREAD

**Issue by wowfredo** [mikaturunen/ng-onload#8]
This morning I did a bower update with this defined in my **bower.json**:
`"ng-onload": "^0.2.1"`

Upon download completion it reads:
`bower ng-onload#^0.2.1                             install ng-onload#0.2.6`

The result, for my use-case, is that it eventually lead to a url mis-reference my script tag. Upon inspecting the ng-onload's bower file, it indeed references version 0.2.6.  I also observed that **0.2.1** is the latest tagged version.  Perhaps my inclusion of the upcaret **("^0.2.1")** is trying to download the latest tagged version which appears to be **0.2.6**:

`Available versions in https://github.com/mikaturunen/ng-onload.git: 0.2.6, 0.2.1, 0.2.0, 0.1.0, 0.0.2, 0.0.1`

And perhaps **0.2.6** might have been tagged in error?  My work-around of course is to define the specific version number, but I wanted to bring this up in case it's helpful.

**Comment by mikaturunen** [comment]
It was due to a bad release, fixed in `0.3.0`. My bad. Thanks for letting me know!

**Comment by wowfredo** [comment]
Thanks!
