### ISSUE TITLE
Bower.json Main Isn't Set for Distribution by Wiredep in Version 0.2.6

### ISSUE THREAD

**Issue by mtpultz** [mikaturunen/ng-onload#9]
Pulling in ngOnload and then having bower postinstall hook run a gulp-wiredep task doesn't inject ngOnload.  Looks like you've got main set to `"lib/ng-onload.js"` and it should be `"release/ng-onload.min.js"`, seems like it is correct in your repo in master and version 0.2.2, but not for version 0.2.6, which is being pulled down by bower since it is the latest.  Currently I'm using `mikaturunen/ng-onload#master` to get the correct bower main value if anyone else needs a quick work around.

**Comment by mikaturunen** [comment]
Yup, I managed to majorly f up the latest release which I'm pushing a fix for. :) Sorry for the trouble folks.

**Comment by mikaturunen** [comment]
There, fixes should be in place in 0.3.0 now 👍

**Comment by mikaturunen** [comment]
Updated the bower json to point to 0.3.0, published new tag to point to the same point and fixed the reference to the distributed file. Thanks for letting me know!

**Comment by mikaturunen** [comment]
If there's more to this issue, reopen it and we'll rock it from there :) Thanks!
